#!/usr/bin/env bash
# Exports the ABIs that a frontend or backend needs into abi/.
#   ./script/export-abi.sh          rewrite abi/*.json and abi/index.ts (typed `as const` exports for viem/wagmi)
#   ./script/export-abi.sh --check  fail if the committed ABIs are out of date (for CI)
set -euo pipefail

cd "$(dirname "$0")/.."
CONTRACTS=(TokenFactory VeztaLaunchToken Token)
MODE="${1:-write}"

forge build --quiet
status=0
for name in "${CONTRACTS[@]}"; do
  fresh="$(forge inspect "$name" abi --json | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), indent=2))')"
  if [ "$MODE" = "--check" ]; then
    if [ "$fresh" != "$(cat "abi/$name.json" 2>/dev/null)" ]; then
      echo "abi/$name.json is out of date: run ./script/export-abi.sh" >&2
      status=1
    fi
  else
    printf '%s\n' "$fresh" > "abi/$name.json"
  fi
done

# abi/index.ts: the same ABIs as `as const` TypeScript so viem and wagmi infer exact types.
index="$(python3 - <<'PY'
import json
names = {"TokenFactory": "tokenFactoryAbi", "VeztaLaunchToken": "launchpadAbi", "Token": "tokenAbi"}
print("// Generated by script/export-abi.sh from the compiled contracts. Do not edit.")
for contract, const in names.items():
    abi = json.load(open(f"abi/{contract}.json"))
    print(f"export const {const} = {json.dumps(abi, indent=2)} as const;")
PY
)"
if [ "$MODE" = "--check" ]; then
  if [ "$index" != "$(cat abi/index.ts 2>/dev/null)" ]; then
    echo "abi/index.ts is out of date: run ./script/export-abi.sh" >&2
    status=1
  fi
  [ "$status" = 0 ] && echo "ABIs are up to date"
else
  printf '%s\n' "$index" > abi/index.ts
fi
exit "$status"
